### ISSUE TITLE
Smooth scroll and sticky nav

### ISSUE THREAD

**Issue by Monal5031** [PiyushPawar17/rush-b#1]
A smooth scroll is missing while clicking on the navbar tabs, also the navbar isn't sticky.
@PiyushPawar17

**Comment by PiyushPawar17** [comment]
@Monal5031 I made this project to learn Sass with React. I'll be updating smooth scrolling when I'll get to know how to do that without external libraries. You can send a PR if you know how it's done.

**Comment by Monal5031** [comment]
:man_facepalming:
